name: larmor
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - matplotlib
  - numpy
  - scipy
  - pip
  - pytest
  - pip:
      - mrsimulator
      - lmfit
      - csdmpy
      - nmrglue
      - fastapi
      - uvicorn[standard]
      - PySide6
      - pyqtgraph
      - requests
      # install LARMOR itself (editable, from this repo)
      - -e .
